name: Sync to Hugging Face Space

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add huggingface https://bitpascals:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/bitpascals/pdf_chatbot
      
      - name: Sync with Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Fetch Hugging Face changes
          git fetch huggingface
          
          # Reset to GitHub's version (keeping your repo as source of truth)
          git reset --hard HEAD
          
          # Force push to Hugging Face (overwrites remote)
          git push huggingface main --force-with-lease
          
          # Alternative safe push (if you want to merge instead of overwrite):
          # git pull huggingface main --allow-unrelated-histories
          # git push huggingface main
